# Copyright 2025 ModelBest Inc. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Tool Alpaca validation metrics for evaluating tool calling accuracy
"""

import json
import re
from typing import Any, Dict, List, Optional

from verl import DataProto


def parse_tool_call(text: str) -> Optional[Dict[str, Any]]:
    """Extract Action and Action_Input from model generated text

    Args:
        text: Generated text from model that should contain Action and Action_Input

    Returns:
        Dict with 'Action' and 'Action_Input' keys, or None if parsing fails
    """
    try:
        # Try to extract "Action: <action_name>"
        action_match = re.search(r"Action\s*:\s*(\w+)", text)
        if not action_match:
            return None
        action = action_match.group(1)

        # Try to extract "Action Input: <json>"
        # Look for JSON between curly braces
        action_input_match = re.search(r"Action\s+Input\s*:\s*(\{.*?\})", text, re.DOTALL)
        if not action_input_match:
            return None

        action_input_str = action_input_match.group(1)
        try:
            action_input = json.loads(action_input_str)
        except json.JSONDecodeError:
            return None

        return {
            "Action": action,
            "Action_Input": action_input
        }
    except Exception:
        return None


def compute_tool_call_accuracy(
    generated_text: str,
    golden_answer: List[Dict[str, Any]],
    fuzzy_match: bool = True
) -> Dict[str, Any]:
    """Compute tool calling accuracy metrics

    Args:
        generated_text: Text generated by the model
        golden_answer: List of expected tool calls from ground truth
        fuzzy_match: If True, use fuzzy matching for parameters (case-insensitive)

    Returns:
        Dict with metrics:
            - "tool_call_accuracy": float in [0, 1]
            - "action_match": bool, whether action name matches first golden answer
            - "param_match": bool, whether parameters match first golden answer
            - "parsed_success": bool, whether parsing was successful
    """
    metrics = {
        "tool_call_accuracy": 0.0,
        "action_match": False,
        "param_match": False,
        "parsed_success": False,
    }

    if not golden_answer or len(golden_answer) == 0:
        return metrics

    # Parse generated text
    parsed = parse_tool_call(generated_text)
    if parsed is None:
        return metrics

    metrics["parsed_success"] = True

    # Compare with first golden answer (we only validate the first tool call)
    golden = golden_answer[0]
    expected_action = golden.get("Action", "")
    expected_input_str = golden.get("Action_Input", "{}")

    # Parse expected input if it's a string
    if isinstance(expected_input_str, str):
        try:
            expected_input = json.loads(expected_input_str)
        except json.JSONDecodeError:
            expected_input = {}
    else:
        expected_input = expected_input_str

    # Check action match
    parsed_action = parsed.get("Action", "")
    if fuzzy_match:
        action_match = parsed_action.lower() == expected_action.lower()
    else:
        action_match = parsed_action == expected_action
    metrics["action_match"] = action_match

    # Check parameter match
    param_match = False
    if action_match:
        parsed_input = parsed.get("Action_Input", {})

        if fuzzy_match:
            # Fuzzy matching: check if all expected keys are present with matching values
            param_match = True
            for key, value in expected_input.items():
                if key not in parsed_input:
                    param_match = False
                    break

                # For string values, do case-insensitive comparison
                if isinstance(value, str) and isinstance(parsed_input[key], str):
                    if value.lower() != parsed_input[key].lower():
                        param_match = False
                        break
                elif value != parsed_input[key]:
                    param_match = False
                    break
        else:
            # Exact matching
            param_match = parsed_input == expected_input

    metrics["param_match"] = param_match

    # Overall accuracy
    if metrics["action_match"] and metrics["param_match"]:
        metrics["tool_call_accuracy"] = 1.0
    elif metrics["action_match"]:
        metrics["tool_call_accuracy"] = 0.5
    else:
        metrics["tool_call_accuracy"] = 0.0

    return metrics


def compute_tool_alpaca_validation_metrics(batch: DataProto) -> Dict[str, List[Any]]:
    """Compute tool calling validation metrics for a batch

    This function extracts generated responses and compares them with
    golden tool calls to compute accuracy metrics.

    Args:
        batch: DataProto batch containing:
            - batch["responses"]: generated response token ids
            - non_tensor_batch["golden_answer"]: expected tool calls

    Returns:
        Dict mapping metric names to lists of values:
            - "tool_call_accuracy": list of accuracy scores [0, 1]
            - "action_match": list of bools
            - "param_match": list of bools
            - "parsed_success": list of bools
    """
    metrics_dict = {
        "tool_call_accuracy": [],
        "action_match": [],
        "param_match": [],
        "parsed_success": [],
    }

    # Get tokenizer from batch if available (set externally if needed)
    tokenizer = getattr(batch, '_tokenizer', None)
    if tokenizer is None:
        # Cannot decode without tokenizer
        return metrics_dict

    # Check if we have the required fields
    if "responses" not in batch.batch or "golden_answer" not in batch.non_tensor_batch:
        return metrics_dict

    responses = batch.batch["responses"]
    golden_answers = batch.non_tensor_batch["golden_answer"]

    batch_size = responses.shape[0]

    # Compute metrics for each sample
    for i in range(batch_size):
        response_ids = responses[i]
        # Decode response tokens
        generated_text = tokenizer.decode(response_ids, skip_special_tokens=True)

        # Get golden answer (should be a list of dicts)
        golden_answer = golden_answers[i]
        if isinstance(golden_answer, str):
            try:
                golden_answer = json.loads(golden_answer)
            except (json.JSONDecodeError, TypeError):
                golden_answer = []

        if not isinstance(golden_answer, list):
            golden_answer = []

        # Compute metrics
        metrics = compute_tool_call_accuracy(generated_text, golden_answer, fuzzy_match=True)

        # Append to result
        metrics_dict["tool_call_accuracy"].append(metrics["tool_call_accuracy"])
        metrics_dict["action_match"].append(1.0 if metrics["action_match"] else 0.0)
        metrics_dict["param_match"].append(1.0 if metrics["param_match"] else 0.0)
        metrics_dict["parsed_success"].append(1.0 if metrics["parsed_success"] else 0.0)

    return metrics_dict


def create_tool_alpaca_val_reward_fn(tokenizer):
    """Create a validation reward function for ToolAlpaca

    Args:
        tokenizer: Tokenizer for decoding responses

    Returns:
        A function compatible with ray_trainer's val_reward_fn
    """
    def val_reward_fn(batch: DataProto, return_dict: bool = False):
        """Evaluate batch and return reward tensor and metrics

        Args:
            batch: DataProto batch
            return_dict: If True, return dict with reward_tensor and reward_extra_info

        Returns:
            If return_dict=True: dict with keys reward_tensor and reward_extra_info
            Otherwise: reward_tensor
        """
        # Temporarily attach tokenizer to batch for metric computation
        batch._tokenizer = tokenizer

        # Compute metrics
        metrics_dict = compute_tool_alpaca_validation_metrics(batch)

        import torch
        import numpy as np

        # Create reward tensor from tool call accuracy
        reward_tensor = torch.tensor(
            metrics_dict["tool_call_accuracy"],
            dtype=torch.float32
        ).unsqueeze(-1)

        if return_dict:
            return {
                "reward_tensor": reward_tensor,
                "reward_extra_info": {
                    "tool_call_acc": metrics_dict["tool_call_accuracy"],
                    "action_match": metrics_dict["action_match"],
                    "param_match": metrics_dict["param_match"],
                    "parse_success": metrics_dict["parsed_success"],
                }
            }
        else:
            return reward_tensor

    return val_reward_fn
